<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-31T19:19:31 IST" name="Suite" finished-at="2023-12-31T19:20:59 IST" duration-ms="88148">
    <groups>
      <group name="ErrorHandling">
        <method signature="errorValidations.loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" name="loginErrorCheck" class="shoppingsite.tests.errorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="purchaseorder">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" name="SubmitOrder" class="shoppingsite.tests.SubmitOrderTest"/>
      </group> <!-- purchaseorder -->
    </groups>
    <test started-at="2023-12-31T19:19:31 IST" name="errorValidations" finished-at="2023-12-31T19:20:52 IST" duration-ms="81185">
      <class name="shoppingsite.tests.errorValidations">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:19:31 IST" name="launchApp" finished-at="2023-12-31T19:20:33 IST" duration-ms="62706" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="ProductNameErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:20:33 IST" name="ProductNameErrorCheck" finished-at="2023-12-31T19:20:49 IST" duration-ms="16018" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at shoppingsite.tests.errorValidations.ProductNameErrorCheck(errorValidations.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNameErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:20:50 IST" name="closeDriver" finished-at="2023-12-31T19:20:50 IST" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:20:50 IST" name="launchApp" finished-at="2023-12-31T19:20:52 IST" duration-ms="1853" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:20:52 IST" name="loginErrorCheck" finished-at="2023-12-31T19:20:52 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@46cdf8bd]" started-at="2023-12-31T19:20:52 IST" name="closeDriver" finished-at="2023-12-31T19:20:52 IST" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- shoppingsite.tests.errorValidations -->
    </test> <!-- errorValidations -->
    <test started-at="2023-12-31T19:19:31 IST" name="SubmitOrderTest" finished-at="2023-12-31T19:20:59 IST" duration-ms="88148">
      <class name="shoppingsite.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:19:31 IST" name="launchApp" finished-at="2023-12-31T19:20:33 IST" duration-ms="62639" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:33 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-12-31T19:20:42 IST" duration-ms="8985" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ZARA COAT 3, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:42 IST" name="closeDriver" finished-at="2023-12-31T19:20:42 IST" duration-ms="64" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:42 IST" name="launchApp" finished-at="2023-12-31T19:20:44 IST" duration-ms="1869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:44 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-12-31T19:20:53 IST" duration-ms="8807" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ADIDAS ORIGINAL, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:53 IST" name="closeDriver" finished-at="2023-12-31T19:20:53 IST" duration-ms="59" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:53 IST" name="launchApp" finished-at="2023-12-31T19:20:55 IST" duration-ms="1932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="OrderHistoryTest(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:55 IST" name="OrderHistoryTest" data-provider="getData" finished-at="2023-12-31T19:20:56 IST" depends-on-methods="shoppingsite.tests.SubmitOrderTest.SubmitOrder" duration-ms="477" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ZARA COAT 3, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at shoppingsite.tests.SubmitOrderTest.OrderHistoryTest(SubmitOrderTest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:56 IST" name="closeDriver" finished-at="2023-12-31T19:20:56 IST" duration-ms="61" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:56 IST" name="launchApp" finished-at="2023-12-31T19:20:58 IST" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="OrderHistoryTest(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:58 IST" name="OrderHistoryTest" data-provider="getData" finished-at="2023-12-31T19:20:58 IST" depends-on-methods="shoppingsite.tests.SubmitOrderTest.SubmitOrder" duration-ms="528" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ADIDAS ORIGINAL, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at shoppingsite.tests.SubmitOrderTest.OrderHistoryTest(SubmitOrderTest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@6253c26]" started-at="2023-12-31T19:20:59 IST" name="closeDriver" finished-at="2023-12-31T19:20:59 IST" duration-ms="59" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- shoppingsite.tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
  </suite> <!-- Suite -->
</testng-results>
